export const graphData = [
    {
      "id": "1",
      "data": {
        "type": "8",
        "typeName": "配偶",
        "nodeType": "",
        "nodes": [
          {
            "children": [],
            "childrenIDs": [],
            "color": "",
            "exist": true,
            "iconType": "spy",
            "id": "d3ff5ef0d9ac4575ab4ca7edbb2ffe08",
            "nodeType": "QB_ZP_RY",
            "oid": "653000197801010123",
            "pid": "",
            "properties": {
              "profession": "劳动工资人员",
              "HJD": "阿克苏地区库车县塔里木乡阿克库勒163",
              "STATE": "社会面",
              "RYBQ": "23、本地有影响的宗教传承体系人员",
              "politicsStatus": "群众",
              "STATE_COLOR": "008800",
              "XM": "海伊提·肉孜",
              "phone": "",
              "PERSON_ID": "2842388",
              "FIVE_ONE_PROPERTY": "商",
              "GENDER": "女",
              "PERSON_DESCRIPTION": "",
              "SFZHM": "653000197801010123"
            },
            "uuid": "d3ff5ef0d9ac4575ab4ca7edbb2ffe08",
            "vid": "QB_ZP_RY__653000197801010123",
            "ownEdges": [],
            "tpids": [],
            "tplxs": {},
            "bsIDs": [],
            "gxmc": "",
            "matchID": [],
            "tpid": "",
            "childCount": 0,
            "tpbhs": [],
            "type": "",
            "keyNode": false
          },
          {
            "children": [],
            "childrenIDs": [],
            "color": "",
            "exist": true,
            "iconType": "spy",
            "id": "dde7715462cd43999572bd515d1ff5af",
            "nodeType": "QB_ZP_RY",
            "oid": "653000197801010123",
            "pid": "",
            "properties": {
              "profession": "劳动工资人员",
              "HJD": "阿克苏地区库车县塔里木乡阿克库勒163",
              "STATE": "社会面",
              "RYBQ": "23、本地有影响的宗教传承体系人员",
              "politicsStatus": "群众",
              "STATE_COLOR": "008800",
              "XM": "海伊提·肉孜",
              "phone": "",
              "PERSON_ID": "2842388",
              "FIVE_ONE_PROPERTY": "商",
              "GENDER": "女",
              "PERSON_DESCRIPTION": "",
              "SFZHM": "653000197801010123"
            },
            "uuid": "dde7715462cd43999572bd515d1ff5af",
            "vid": "QB_ZP_RY__653000197801010123",
            "ownEdges": [],
            "tpids": [],
            "tplxs": {},
            "bsIDs": [],
            "gxmc": "",
            "matchID": [],
            "tpid": "",
            "childCount": 0,
            "tpbhs": [],
            "type": "",
            "keyNode": false
          },
          {
            "children": [],
            "childrenIDs": [],
            "color": "",
            "exist": true,
            "iconType": "spy",
            "id": "0f82a75461bd466f96123b7657b7e50a",
            "nodeType": "QB_ZP_RY",
            "oid": "653000197801010126",
            "pid": "",
            "properties": {
              "profession": "劳动工资人员",
              "HJD": "阿克苏地区库车县塔里木乡阿克库勒166",
              "STATE": "收教",
              "RYBQ": "26、境外加入世维会组织人员",
              "politicsStatus": "群众",
              "STATE_COLOR": "f7b940",
              "XM": "艾尔克·肉孜",
              "phone": "",
              "PERSON_ID": "2842387",
              "FIVE_ONE_PROPERTY": "政",
              "GENDER": "女",
              "PERSON_DESCRIPTION": "",
              "SFZHM": "653000197801010126"
            },
            "uuid": "0f82a75461bd466f96123b7657b7e50a",
            "vid": "QB_ZP_RY__653000197801010126",
            "ownEdges": [],
            "tpids": [],
            "tplxs": {},
            "bsIDs": [],
            "gxmc": "",
            "matchID": [],
            "tpid": "",
            "childCount": 0,
            "tpbhs": [],
            "type": "",
            "keyNode": false
          },
          {
            "children": [],
            "childrenIDs": [],
            "color": "",
            "exist": true,
            "iconType": "spy",
            "id": "22437e805d994c01bd99cd14465cfa82",
            "nodeType": "QB_ZP_RY",
            "oid": "653000197801010126",
            "pid": "",
            "properties": {
              "profession": "劳动工资人员",
              "HJD": "阿克苏地区库车县塔里木乡阿克库勒166",
              "STATE": "收教",
              "RYBQ": "26、境外加入世维会组织人员",
              "politicsStatus": "群众",
              "STATE_COLOR": "f7b940",
              "XM": "艾尔克·肉孜",
              "phone": "",
              "PERSON_ID": "2842387",
              "FIVE_ONE_PROPERTY": "政",
              "GENDER": "女",
              "PERSON_DESCRIPTION": "",
              "SFZHM": "653000197801010126"
            },
            "uuid": "22437e805d994c01bd99cd14465cfa82",
            "vid": "QB_ZP_RY__653000197801010126",
            "ownEdges": [],
            "tpids": [],
            "tplxs": {},
            "bsIDs": [],
            "gxmc": "",
            "matchID": [],
            "tpid": "",
            "childCount": 0,
            "tpbhs": [],
            "type": "",
            "keyNode": false
          }
        ]
      }
    },
    {
      "id": "2",
      "data": {
        "type": "9",
        "typeName": "前配偶",
        "nodeType": "",
        "nodes": [
          {
            "children": [],
            "childrenIDs": [],
            "color": "",
            "exist": true,
            "iconType": "spy",
            "id": "835e3d31c24d4ab5b493b44977dd2433",
            "nodeType": "QB_ZP_RY",
            "oid": "652900197801010128",
            "pid": "",
            "properties": {
              "profession": "劳动工资人员",
              "HJD": "阿克苏地区库车县塔里木乡阿克库勒148",
              "STATE": "收教",
              "RYBQ": "18、涉嫌埃及学经人员,8、历年来打击处理人员",
              "politicsStatus": "台盟盟员",
              "STATE_COLOR": "f7b940",
              "XM": "板合提亚尔·买买提",
              "phone": "13257591077",
              "PERSON_ID": "2842394",
              "FIVE_ONE_PROPERTY": "商",
              "GENDER": "女",
              "PERSON_DESCRIPTION": "",
              "SFZHM": "652900197801010128"
            },
            "uuid": "835e3d31c24d4ab5b493b44977dd2433",
            "vid": "QB_ZP_RY__652900197801010128",
            "ownEdges": [],
            "tpids": [],
            "tplxs": {},
            "bsIDs": [],
            "gxmc": "",
            "matchID": [],
            "tpid": "",
            "childCount": 0,
            "tpbhs": [],
            "type": "",
            "keyNode": false
          },
          {
            "children": [],
            "childrenIDs": [],
            "color": "",
            "exist": true,
            "iconType": "spy",
            "id": "77aaa32d08a54460876715a307141fbc",
            "nodeType": "QB_ZP_RY",
            "oid": "652900197801010128",
            "pid": "",
            "properties": {
              "profession": "劳动工资人员",
              "HJD": "阿克苏地区库车县塔里木乡阿克库勒148",
              "STATE": "收教",
              "RYBQ": "18、涉嫌埃及学经人员,8、历年来打击处理人员",
              "politicsStatus": "台盟盟员",
              "STATE_COLOR": "f7b940",
              "XM": "板合提亚尔·买买提",
              "phone": "13257591077",
              "PERSON_ID": "2842394",
              "FIVE_ONE_PROPERTY": "商",
              "GENDER": "女",
              "PERSON_DESCRIPTION": "",
              "SFZHM": "652900197801010128"
            },
            "uuid": "77aaa32d08a54460876715a307141fbc",
            "vid": "QB_ZP_RY__652900197801010128",
            "ownEdges": [],
            "tpids": [],
            "tplxs": {},
            "bsIDs": [],
            "gxmc": "",
            "matchID": [],
            "tpid": "",
            "childCount": 0,
            "tpbhs": [],
            "type": "",
            "keyNode": false
          }
        ]
      }
    },
    {
      "id": "3",
      "data": {
        "type": "10",
        "typeName": "儿子",
        "nodeType": "",
        "nodes": [
          {
            "children": [],
            "childrenIDs": [],
            "color": "",
            "exist": true,
            "iconType": "spy",
            "id": "7fd65abaa1494666a263dddb2e2a71d7",
            "nodeType": "QB_ZP_RY",
            "oid": "653000197801010122",
            "pid": "",
            "properties": {
              "profession": "劳动工资人员",
              "HJD": "阿克苏地区库车县塔里木乡阿克库勒162",
              "STATE": "去向不明",
              "RYBQ": "22、“阿·买合苏木”传承体系人员",
              "politicsStatus": "群众",
              "STATE_COLOR": "0000fe",
              "XM": "吐尔逊·肉孜",
              "phone": "",
              "PERSON_ID": "2842384",
              "FIVE_ONE_PROPERTY": "宗",
              "GENDER": "女",
              "PERSON_DESCRIPTION": "",
              "SFZHM": "653000197801010122"
            },
            "uuid": "7fd65abaa1494666a263dddb2e2a71d7",
            "vid": "QB_ZP_RY__653000197801010122",
            "ownEdges": [],
            "tpids": [],
            "tplxs": {},
            "bsIDs": [],
            "gxmc": "",
            "matchID": [],
            "tpid": "",
            "childCount": 0,
            "tpbhs": [],
            "type": "",
            "keyNode": false
          },
          {
            "children": [],
            "childrenIDs": [],
            "color": "",
            "exist": true,
            "iconType": "spy",
            "id": "7b26251bf196415aad7456f8323191b0",
            "nodeType": "QB_ZP_RY",
            "oid": "653000197801010122",
            "pid": "",
            "properties": {
              "profession": "劳动工资人员",
              "HJD": "阿克苏地区库车县塔里木乡阿克库勒162",
              "STATE": "去向不明",
              "RYBQ": "22、“阿·买合苏木”传承体系人员",
              "politicsStatus": "群众",
              "STATE_COLOR": "0000fe",
              "XM": "吐尔逊·肉孜",
              "phone": "",
              "PERSON_ID": "2842384",
              "FIVE_ONE_PROPERTY": "宗",
              "GENDER": "女",
              "PERSON_DESCRIPTION": "",
              "SFZHM": "653000197801010122"
            },
            "uuid": "7b26251bf196415aad7456f8323191b0",
            "vid": "QB_ZP_RY__653000197801010122",
            "ownEdges": [],
            "tpids": [],
            "tplxs": {},
            "bsIDs": [],
            "gxmc": "",
            "matchID": [],
            "tpid": "",
            "childCount": 0,
            "tpbhs": [],
            "type": "",
            "keyNode": false
          },
          {
            "children": [],
            "childrenIDs": [],
            "color": "",
            "exist": true,
            "iconType": "spy",
            "id": "634c6d2c26d24cbdb988caf79f7b5a08",
            "nodeType": "QB_ZP_RY",
            "oid": "653000197801010124",
            "pid": "",
            "properties": {
              "profession": "劳动工资人员",
              "HJD": "阿克苏地区库车县塔里木乡阿克库勒164",
              "STATE": "死亡",
              "RYBQ": "24、阿克苏籍出境未归人员",
              "politicsStatus": "群众",
              "STATE_COLOR": "6B6B6B",
              "XM": "库尔班·肉孜",
              "phone": "",
              "PERSON_ID": "2842389",
              "FIVE_ONE_PROPERTY": "恐",
              "GENDER": "女",
              "PERSON_DESCRIPTION": "",
              "SFZHM": "653000197801010124"
            },
            "uuid": "634c6d2c26d24cbdb988caf79f7b5a08",
            "vid": "QB_ZP_RY__653000197801010124",
            "ownEdges": [],
            "tpids": [],
            "tplxs": {},
            "bsIDs": [],
            "gxmc": "",
            "matchID": [],
            "tpid": "",
            "childCount": 0,
            "tpbhs": [],
            "type": "",
            "keyNode": false
          },
          {
            "children": [],
            "childrenIDs": [],
            "color": "",
            "exist": true,
            "iconType": "spy",
            "id": "475265fcdf5f4edb91d54366eeadb7a1",
            "nodeType": "QB_ZP_RY",
            "oid": "653000197801010124",
            "pid": "",
            "properties": {
              "profession": "劳动工资人员",
              "HJD": "阿克苏地区库车县塔里木乡阿克库勒164",
              "STATE": "死亡",
              "RYBQ": "24、阿克苏籍出境未归人员",
              "politicsStatus": "群众",
              "STATE_COLOR": "6B6B6B",
              "XM": "库尔班·肉孜",
              "phone": "",
              "PERSON_ID": "2842389",
              "FIVE_ONE_PROPERTY": "恐",
              "GENDER": "女",
              "PERSON_DESCRIPTION": "",
              "SFZHM": "653000197801010124"
            },
            "uuid": "475265fcdf5f4edb91d54366eeadb7a1",
            "vid": "QB_ZP_RY__653000197801010124",
            "ownEdges": [],
            "tpids": [],
            "tplxs": {},
            "bsIDs": [],
            "gxmc": "",
            "matchID": [],
            "tpid": "",
            "childCount": 0,
            "tpbhs": [],
            "type": "",
            "keyNode": false
          },
          {
            "children": [],
            "childrenIDs": [],
            "color": "",
            "exist": true,
            "iconType": "spy",
            "id": "2988f1828b7a4ad88b45635669f13c6b",
            "nodeType": "QB_ZP_RY",
            "oid": "653000197801010125",
            "pid": "",
            "properties": {
              "profession": "劳动工资人员",
              "HJD": "阿克苏地区库车县塔里木乡阿克库勒165",
              "STATE": "收押",
              "RYBQ": "25、境外加入东伊运人员",
              "politicsStatus": "群众",
              "STATE_COLOR": "cb4324",
              "XM": "托合提·肉孜",
              "phone": "",
              "PERSON_ID": "2842386",
              "FIVE_ONE_PROPERTY": "黑",
              "GENDER": "女",
              "PERSON_DESCRIPTION": "",
              "SFZHM": "653000197801010125"
            },
            "uuid": "2988f1828b7a4ad88b45635669f13c6b",
            "vid": "QB_ZP_RY__653000197801010125",
            "ownEdges": [],
            "tpids": [],
            "tplxs": {},
            "bsIDs": [],
            "gxmc": "",
            "matchID": [],
            "tpid": "",
            "childCount": 0,
            "tpbhs": [],
            "type": "",
            "keyNode": false
          },
          {
            "children": [],
            "childrenIDs": [],
            "color": "",
            "exist": true,
            "iconType": "spy",
            "id": "fbfecf58f63749ae9b0635b3b3ba5b58",
            "nodeType": "QB_ZP_RY",
            "oid": "653000197801010125",
            "pid": "",
            "properties": {
              "profession": "劳动工资人员",
              "HJD": "阿克苏地区库车县塔里木乡阿克库勒165",
              "STATE": "收押",
              "RYBQ": "25、境外加入东伊运人员",
              "politicsStatus": "群众",
              "STATE_COLOR": "cb4324",
              "XM": "托合提·肉孜",
              "phone": "",
              "PERSON_ID": "2842386",
              "FIVE_ONE_PROPERTY": "黑",
              "GENDER": "女",
              "PERSON_DESCRIPTION": "",
              "SFZHM": "653000197801010125"
            },
            "uuid": "fbfecf58f63749ae9b0635b3b3ba5b58",
            "vid": "QB_ZP_RY__653000197801010125",
            "ownEdges": [],
            "tpids": [],
            "tplxs": {},
            "bsIDs": [],
            "gxmc": "",
            "matchID": [],
            "tpid": "",
            "childCount": 0,
            "tpbhs": [],
            "type": "",
            "keyNode": false
          },
          {
            "children": [],
            "childrenIDs": [],
            "color": "",
            "exist": true,
            "iconType": "spy",
            "id": "5d6d09bc2416429bb418ce6db827a204",
            "nodeType": "QB_ZP_RY",
            "oid": "653000197801010128",
            "pid": "",
            "properties": {
              "profession": "劳动工资人员",
              "HJD": "阿克苏地区库车县塔里木乡阿克库勒168",
              "STATE": "去向不明",
              "RYBQ": "28、疑似加入恐怖组织人员",
              "politicsStatus": "群众",
              "STATE_COLOR": "0000fe",
              "XM": "板合提亚尔·肉孜",
              "phone": "13257591079",
              "PERSON_ID": "2842392",
              "FIVE_ONE_PROPERTY": "商",
              "GENDER": "女",
              "PERSON_DESCRIPTION": "",
              "SFZHM": "653000197801010128"
            },
            "uuid": "5d6d09bc2416429bb418ce6db827a204",
            "vid": "QB_ZP_RY__653000197801010128",
            "ownEdges": [],
            "tpids": [],
            "tplxs": {},
            "bsIDs": [],
            "gxmc": "",
            "matchID": [],
            "tpid": "",
            "childCount": 0,
            "tpbhs": [],
            "type": "",
            "keyNode": false
          },
          {
            "children": [],
            "childrenIDs": [],
            "color": "",
            "exist": true,
            "iconType": "spy",
            "id": "eae237dbc458451fbd0638ecd5392017",
            "nodeType": "QB_ZP_RY",
            "oid": "653000197801010128",
            "pid": "",
            "properties": {
              "profession": "劳动工资人员",
              "HJD": "阿克苏地区库车县塔里木乡阿克库勒168",
              "STATE": "去向不明",
              "RYBQ": "28、疑似加入恐怖组织人员",
              "politicsStatus": "群众",
              "STATE_COLOR": "0000fe",
              "XM": "板合提亚尔·肉孜",
              "phone": "13257591079",
              "PERSON_ID": "2842392",
              "FIVE_ONE_PROPERTY": "商",
              "GENDER": "女",
              "PERSON_DESCRIPTION": "",
              "SFZHM": "653000197801010128"
            },
            "uuid": "eae237dbc458451fbd0638ecd5392017",
            "vid": "QB_ZP_RY__653000197801010128",
            "ownEdges": [],
            "tpids": [],
            "tplxs": {},
            "bsIDs": [],
            "gxmc": "",
            "matchID": [],
            "tpid": "",
            "childCount": 0,
            "tpbhs": [],
            "type": "",
            "keyNode": false
          }
        ]
      }
    },
    {
      "id": "4",
      "data": {
        "type": "11",
        "typeName": "女儿",
        "nodeType": "",
        "nodes": [
          {
            "children": [],
            "childrenIDs": [],
            "color": "",
            "exist": true,
            "iconType": "spy",
            "id": "4a1b1bbccb93492d953e31ff63319016",
            "nodeType": "QB_ZP_RY",
            "oid": "653000197801010127",
            "pid": "",
            "properties": {
              "profession": "劳动工资人员",
              "HJD": "阿克苏地区库车县塔里木乡阿克库勒167",
              "STATE": "境外",
              "RYBQ": "27、境外加入IS组织人员",
              "politicsStatus": "群众",
              "STATE_COLOR": "ffe900",
              "XM": "尼贾提·肉孜",
              "phone": "",
              "PERSON_ID": "2842391",
              "FIVE_ONE_PROPERTY": "宗",
              "GENDER": "女",
              "PERSON_DESCRIPTION": "",
              "SFZHM": "653000197801010127"
            },
            "uuid": "4a1b1bbccb93492d953e31ff63319016",
            "vid": "QB_ZP_RY__653000197801010127",
            "ownEdges": [],
            "tpids": [],
            "tplxs": {},
            "bsIDs": [],
            "gxmc": "",
            "matchID": [],
            "tpid": "",
            "childCount": 0,
            "tpbhs": [],
            "type": "",
            "keyNode": false
          },
          {
            "children": [],
            "childrenIDs": [],
            "color": "",
            "exist": true,
            "iconType": "spy",
            "id": "ca15ca3e5eee42bfbeabc8c64e25311e",
            "nodeType": "QB_ZP_RY",
            "oid": "653000197801010127",
            "pid": "",
            "properties": {
              "profession": "劳动工资人员",
              "HJD": "阿克苏地区库车县塔里木乡阿克库勒167",
              "STATE": "境外",
              "RYBQ": "27、境外加入IS组织人员",
              "politicsStatus": "群众",
              "STATE_COLOR": "ffe900",
              "XM": "尼贾提·肉孜",
              "phone": "",
              "PERSON_ID": "2842391",
              "FIVE_ONE_PROPERTY": "宗",
              "GENDER": "女",
              "PERSON_DESCRIPTION": "",
              "SFZHM": "653000197801010127"
            },
            "uuid": "ca15ca3e5eee42bfbeabc8c64e25311e",
            "vid": "QB_ZP_RY__653000197801010127",
            "ownEdges": [],
            "tpids": [],
            "tplxs": {},
            "bsIDs": [],
            "gxmc": "",
            "matchID": [],
            "tpid": "",
            "childCount": 0,
            "tpbhs": [],
            "type": "",
            "keyNode": false
          }
        ]
      }
    }
  ]