/*
 * @Description: In User Settings Edit
 * @Author: your name
 * @Date: 2019-09-04 14:01:03
 * @LastEditTime: 2019-09-04 14:01:03
 * @LastEditors: your name
 */
export const graphData = {
  "children": [{
    "children": [{
      "children": [{
          "children": [{
            "children": [],
            "childrenIDs": [],
            "color": "",
            "exist": true,
            "iconType": "spy",
            "id": "1010d33004434ab89a9376add5f98479",
            "nodeType": "QB_ZP_RY",
            "oid": "653000197801010123",
            "pid": "",
            "properties": {
              "profession": "",
              "HJD": "市辖区东城区东华门街道多福巷社区村163",
              "STATE": "社会面",
              "RYBQ": "23、本地有影响的宗教传承体系人员",
              "politicsStatus": "",
              "STATE_COLOR": "008800",
              "XM": "海伊提·肉孜",
              "phone": "",
              "PERSON_ID": "2842388",
              "FIVE_ONE_PROPERTY": "",
              "GENDER": "女",
              "PERSON_DESCRIPTION": "1",
              "SFZHM": "653000197801010123"
            },
            "uuid": "1010d33004434ab89a9376add5f98479",
            "vid": "QB_ZP_RY__653000197801010123",
            "ownEdges": [],
            "tpids": [],
            "tplxs": {},
            "bsIDs": [],
            "gxmc": "",
            "matchID": [],
            "tpid": "",
            "childCount": 0,
            "tpbhs": [],
            "type": "",
            "keyNode": false
          }],
          "childrenIDs": [],
          "color": "",
          "exist": true,
          "iconType": "",
          "id": "fef2c708883647adb8c8fda84bcee2c4",
          "nodeType": "",
          "oid": "fef2c708883647adb8c8fda84bcee2c4",
          "pid": "",
          "properties": {},
          "uuid": "fef2c708883647adb8c8fda84bcee2c4",
          "vid": "__fef2c708883647adb8c8fda84bcee2c4",
          "ownEdges": [],
          "tpids": [],
          "tplxs": {},
          "bsIDs": [],
          "gxmc": "",
          "matchID": [],
          "tpid": "",
          "childCount": 0,
          "tpbhs": [],
          "type": "配偶",
          "keyNode": false
        },
        {
          "children": [{
              "children": [],
              "childrenIDs": [],
              "color": "",
              "exist": true,
              "iconType": "spy",
              "id": "1abce3f0f31b4bd4b661a4882fd7b8d4",
              "nodeType": "QB_ZP_RY",
              "oid": "653000197801010122",
              "pid": "",
              "properties": {
                "profession": "",
                "HJD": "乌鲁木齐市天山区燕儿窝街道燕儿窝南社区村333",
                "STATE": "去向不明",
                "RYBQ": "22、“阿·买合苏木”传承体系人员",
                "politicsStatus": "",
                "STATE_COLOR": "0000fe",
                "XM": "吐尔逊·肉孜d",
                "phone": "",
                "PERSON_ID": "2842384",
                "FIVE_ONE_PROPERTY": "",
                "GENDER": "女",
                "PERSON_DESCRIPTION": "3",
                "SFZHM": "653000197801010122"
              },
              "uuid": "1abce3f0f31b4bd4b661a4882fd7b8d4",
              "vid": "QB_ZP_RY__653000197801010122",
              "ownEdges": [],
              "tpids": [],
              "tplxs": {},
              "bsIDs": [],
              "gxmc": "",
              "matchID": [],
              "tpid": "",
              "childCount": 0,
              "tpbhs": [],
              "type": "",
              "keyNode": false
            },
            {
              "children": [],
              "childrenIDs": [],
              "color": "",
              "exist": true,
              "iconType": "spy",
              "id": "eb76dc8b6df945968275afad9dd2f075",
              "nodeType": "QB_ZP_RY",
              "oid": "653000197801010124",
              "pid": "",
              "properties": {
                "profession": "劳动工资人员",
                "HJD": "阿克苏地区库车县塔里木乡阿克库勒164",
                "STATE": "死亡",
                "RYBQ": "24、阿克苏籍出境未归人员",
                "politicsStatus": "群众",
                "STATE_COLOR": "6B6B6B",
                "XM": "库尔班·肉孜",
                "phone": "",
                "PERSON_ID": "2842389",
                "FIVE_ONE_PROPERTY": "恐",
                "GENDER": "女",
                "PERSON_DESCRIPTION": "",
                "SFZHM": "653000197801010124"
              },
              "uuid": "eb76dc8b6df945968275afad9dd2f075",
              "vid": "QB_ZP_RY__653000197801010124",
              "ownEdges": [],
              "tpids": [],
              "tplxs": {},
              "bsIDs": [],
              "gxmc": "",
              "matchID": [],
              "tpid": "",
              "childCount": 0,
              "tpbhs": [],
              "type": "",
              "keyNode": false
            },
            {
              "children": [],
              "childrenIDs": [],
              "color": "",
              "exist": true,
              "iconType": "spy",
              "id": "6dedcc2f12cd41bcb0c21c3281a16b19",
              "nodeType": "QB_ZP_RY",
              "oid": "653000197801010125",
              "pid": "",
              "properties": {
                "profession": "劳动工资人员",
                "HJD": "阿克苏地区库车县塔里木乡阿克库勒165",
                "STATE": "收押",
                "RYBQ": "25、境外加入东伊运人员",
                "politicsStatus": "群众",
                "STATE_COLOR": "cb4324",
                "XM": "托合提·肉孜",
                "phone": "",
                "PERSON_ID": "2842386",
                "FIVE_ONE_PROPERTY": "黑",
                "GENDER": "女",
                "PERSON_DESCRIPTION": "",
                "SFZHM": "653000197801010125"
              },
              "uuid": "6dedcc2f12cd41bcb0c21c3281a16b19",
              "vid": "QB_ZP_RY__653000197801010125",
              "ownEdges": [],
              "tpids": [],
              "tplxs": {},
              "bsIDs": [],
              "gxmc": "",
              "matchID": [],
              "tpid": "",
              "childCount": 0,
              "tpbhs": [],
              "type": "",
              "keyNode": false
            }
          ],
          "childrenIDs": [],
          "color": "",
          "exist": true,
          "iconType": "",
          "id": "0423ef00310541b8b685c4cc3a3880ff",
          "nodeType": "",
          "oid": "0423ef00310541b8b685c4cc3a3880ff",
          "pid": "",
          "properties": {},
          "uuid": "0423ef00310541b8b685c4cc3a3880ff",
          "vid": "__0423ef00310541b8b685c4cc3a3880ff",
          "ownEdges": [],
          "tpids": [],
          "tplxs": {},
          "bsIDs": [],
          "gxmc": "",
          "matchID": [],
          "tpid": "",
          "childCount": 0,
          "tpbhs": [],
          "type": "儿子",
          "keyNode": false
        }
      ],
      "childrenIDs": [
        "653000197801010124",
        "653000197801010125",
        "653000197801010122",
        "653000197801010123"
      ],
      "color": "",
      "exist": true,
      "iconType": "spy",
      "id": "210a33bfeddd45a4ba3c2f9e81010bf0",
      "nodeType": "QB_ZP_RY",
      "oid": "653000197801010121",
      "pid": "",
      "properties": {
        "profession": "劳动工资人员",
        "HJD": "阿克苏地区库车县塔里木乡阿克库勒161",
        "STATE": "境外",
        "RYBQ": "21、荒地教经堂”传承体系人员",
        "politicsStatus": "群众",
        "STATE_COLOR": "ffe900",
        "XM": "吐尔地·肉孜",
        "phone": "",
        "PERSON_ID": "2842383",
        "FIVE_ONE_PROPERTY": "政",
        "GENDER": "女",
        "PERSON_DESCRIPTION": "",
        "SFZHM": "653000197801010121"
      },
      "uuid": "210a33bfeddd45a4ba3c2f9e81010bf0",
      "vid": "QB_ZP_RY__653000197801010121",
      "ownEdges": [],
      "tpids": [],
      "tplxs": {},
      "bsIDs": [],
      "gxmc": null,
      "matchID": [],
      "tpid": "",
      "childCount": 0,
      "tpbhs": [],
      "type": "",
      "keyNode": false
    }],
    "childrenIDs": [],
    "color": "",
    "exist": false,
    "iconType": "spy",
    "id": "root",
    "nodeType": "QB",
    "oid": "root",
    "pid": "",
    "properties": {},
    "uuid": "root",
    "vid": "QB__root",
    "ownEdges": [],
    "tpids": [],
    "tplxs": {},
    "bsIDs": [],
    "gxmc": "",
    "matchID": [],
    "tpid": "",
    "childCount": 0,
    "tpbhs": [],
    "type": "",
    "keyNode": false
  }],
  "childrenIDs": [],
  "color": "",
  "exist": false,
  "iconType": "spy",
  "id": "root",
  "nodeType": "QB",
  "oid": "root",
  "pid": "",
  "properties": {},
  "uuid": "root",
  "vid": "QB__root",
  "ownEdges": [],
  "tpids": [],
  "tplxs": {},
  "bsIDs": [],
  "gxmc": "",
  "matchID": [],
  "tpid": "",
  "childCount": 0,
  "tpbhs": [],
  "type": "",
  "keyNode": false
}
