/*
 * @Description: In User Settings Edit
 * @Author: your name
 * @Date: 2019-08-29 16:44:36
 * @LastEditTime: 2019-12-17 16:51:53
 * @LastEditors: Please set LastEditors
 */
export const ERR_OK = 200 //成功

//清单list
export const OPTIONS_LIST = {
  GENDER: "GENDER", //性别
  NATIONALITY: "NATIONALITY", //民族
  PERSON_TAG: "PERSON_TAG", //标签
  STATE_STRONG: "STATE_STRONG", //人员状态(大类
  FIVE_ONE_PROPERTY: "FIVE_ONE_PROPERTY", //五位一体属性
  POLITICS_STATUS: "POLITICS_STATUS", //政治面貌
  PROFESSION: "PROFESSION", //职业
  STATE_DETAIL: "STATE_DETAIL", //人员状态(细类)
  DEPT_TREE: "DEPT_TREE", //部门单位树的数据
  CURRENT_TOKEN_DEPT_TREE: "CURRENT_TOKEN_DEPT_TREE", //当前用户的部门单位树的数据
  CITY_AREA_TREE: "CITY_AREA_TREE", //归属区划的数据
  BELONG_PROVICE: "BELONG_PROVICE", //全国省的数据
  BELONG_AKS_CITY: "BELONG_AKS_CITY", //阿克苏地区的数据
  PROCESS_RESULT: "PROCESS_RESULT", //处理结果
  CASE_RELATION: "CASE_RELATION", //成员身份
  CASE_TYPE: "CASE_TYPE", //案件类别
  CASE_BELONG_THREE_ONE: "CASE_BELONG_THREE_ONE", //三党两集团一组织
  CASE_PROCESS_RESULT: "CASE_PROCESS_RESULT", //案件处理结果
  OVERSEAS_SKSB_PERSON: "OVERSEAS_SKSB_PERSON", //是否是境外涉恐涉暴人员
  OUTBOUND_REASON: "OUTBOUND_REASON", //出境理由
  BKQK: "BKQK", //边控情况
  ZTQK: "ZTQK", //追逃情况
  EXIT_MEASURES: "EXIT_MEASURES", //出境方法
  OUTBOUND_WAY: "OUTBOUND_WAY", //出境方式
  EXIT_CHANNEL: "EXIT_CHANNEL", //出境通道
  EXIT_PERSON_CATEGORY: "EXIT_PERSON_CATEGORY", //出境人员类别
  EXIT_PRESENT: "EXIT_PRESENT", //境外现状
  EXIT_RELATION_NAME: "EXIT_RELATION_NAME", //出入境关系
  OUTBOUND_TO_COUNTRY: "OUTBOUND_TO_COUNTRY", //目前所在国家
  DATA_AUTH: "DATA_AUTH", //用户组中数据授权
  HELP_TYPE: "HELP_TYPE", //提供何种帮助
  PILGRIMAGE_TYPE: "PILGRIMAGE_TYPE", //朝觐类型
  OUTBOUND_IS_CANCEL: "OUTBOUND_IS_CANCEL", //是否注销中国国籍
  OUTBOUND_CERTIFICATE_TYPE: "OUTBOUND_CERTIFICATE_TYPE", // 出国证件种类
  SHORT_MAP_TYPE: "SHORT_MAP_TYPE", // 所有类型图谱
  SHORT_MAP_TYPE_FOR_ANALYSIS: "SHORT_MAP_TYPE_FOR_ANALYSIS", // 需要展示的类型图谱
  CASE_CLUE_CATEGORY: "CASE_CLUE_CATEGORY", //案件线索类别
  CASE_CLUE_TYPE: "CASE_CLUE_TYPE", //案件线索类型
  CASE_CLUE_SOURCE: "CASE_CLUE_SOURCE", //案件线索来源
  CASE_CLUE_STATE: "CASE_CLUE_STATE", //案件线索状态
  AGENCY_TYPE: "AGENCY_TYPE", //村以及寺庙状态
  PUBLISH_TYPE: "PUBLISH_TYPE", //发布类型
  PARTY_POSITION: "PARTY_POSITION", //村两委职位
  MOSQUE_POSITION: "MOSQUE_POSITION", //清真寺职位
}

export const CASE_CODE = '案件';
export const CLUB_CODE = '线索';
